os: linux
dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-9
    packages:
      - clang-9
env:
  - MATRIX_EVAL="CC=clang-9 && CXX=clang-9"
before_install:
  - eval "${MATRIX_EVAL}"
script:
- cmake .
- cmake --build .



