os: linux
dist: xenial
language: cpp
compiler: clang
addons:
  apt:
    sources:
      - llvm-toolchain-trusty-8
    packages:
      - clang-8
env:
  - MATRIX_EVAL="CC=clang-8 && CXX=clang-8"
before_install:
  - eval "${MATRIX_EVAL}"
script:
- cmake .
- cmake --build .



